/**
 * Action Registry & Command Dispatcher for Spartan Games AI
 * Implements the Dispatcher Pattern to eliminate cascading regex chains.
 * Follows the Open/Closed Principle: new actions are added as handlers
 * without altering the parsing engine.
 */

export const ACTION_HANDLERS = {
  // Direct actions (no payload)
  builder: () => ({
    type: "builder",
    label: "Armar PC personalizada"
  }),

  catalog: () => ({
    type: "catalog",
    label: "Ver catálogo"
  }),

  cart: () => ({
    type: "cart",
    label: "Ver carrito"
  }),

  maps: () => ({
    type: "maps",
    label: "Ubicación en Google Maps"
  }),

  waze: () => ({
    type: "waze",
    label: "Ruta en Waze"
  }),

  faq: () => ({
    type: "faq",
    label: "Preguntas Frecuentes y Garantías"
  }),

  categories: () => ({
    type: "categories",
    label: "Explorar Categorías"
  }),

  facebook: () => ({
    type: "facebook",
    label: "Facebook oficial"
  }),

  instagram: () => ({
    type: "instagram",
    label: "Instagram oficial"
  }),

  tiktok: () => ({
    type: "tiktok",
    label: "TikTok oficial"
  }),

  // Actions with free-text payload
  whatsapp: (payload) => ({
    type: "whatsapp",
    text: payload ? payload.trim() : "Hola Spartan Games, deseo realizar una consulta sobre sus productos",
    label: "Consultar por WhatsApp"
  }),

  // Actions with structured array payload (IDs)
  addtocart: (payload) => {
    if (!payload) return null;
    const ids = payload
      .split(/[,;\s]+/)
      .map((s) => s.trim())
      .filter(Boolean);

    return ids.length > 0
      ? {
          type: "add_to_cart_batch",
          productIds: ids,
          label: `🛒 Agregar cotización al carrito (${ids.length} componentes)`
        }
      : null;
  }
};

/**
 * Normalizes aliases, accents, and alternative names generated by LLMs
 */
export const ACTION_ALIASES = {
  pc_builder: "builder",
  pcbuilder: "builder",
  armar: "builder",
  armar_pc: "builder",
  configurador: "builder",

  catalogo: "catalog",
  catálogo: "catalog",
  catalogue: "catalog",
  tienda: "catalog",
  store: "catalog",
  productos: "catalog",

  open_cart: "cart",
  opencart: "cart",
  ver_carrito: "cart",
  vercarrito: "cart",

  map: "maps",
  mapa: "maps",
  ubicacion: "maps",
  ubicación: "maps",
  location: "maps",
  google_maps: "maps",
  googlemaps: "maps",
  google_map: "maps",
  googlemap: "maps",

  gps: "waze",
  ruta_waze: "waze",

  preguntas: "faq",
  preguntas_frecuentes: "faq",
  garantia: "faq",
  garantía: "faq",
  garantias: "faq",
  garantías: "faq",
  politica: "faq",
  política: "faq",
  politicas: "faq",
  políticas: "faq",

  categorias: "categories",
  categorías: "categories",
  hardware: "categories",
  departamentos: "categories",

  wsp: "whatsapp",
  wa: "whatsapp",

  add_to_cart: "addtocart",
  carrito: "addtocart",
  agregar_carrito: "addtocart",
  cotizacion: "addtocart",
  cotización: "addtocart"
};

/**
 * Dispatches an action name and payload to its registered handler
 * @param {string} rawCommand
 * @param {string} [payload]
 * @returns {object|null}
 */
export function dispatchAction(rawCommand, payload) {
  if (!rawCommand) return null;
  const normalizedKey = rawCommand.toLowerCase().trim();
  const targetKey = ACTION_ALIASES[normalizedKey] || normalizedKey;
  const handler = ACTION_HANDLERS[targetKey];

  if (typeof handler === "function") {
    return handler(payload);
  }

  return null;
}
